sonar.projectKey=Sisinfo
sonar.projectName=Sisinfo
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.test=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/seed/**, **/components/ui/*.tsx, apps/web/src/app/globals.css, test/*.ts
sonar.javascript.lcov.reportPaths=coverage/api/lcov.info,coverage/web/lcov.info